version: '3.9'

services:
  rdb:
    container_name: url_shortener_db
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./rdb_volume:/data
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge

